### ISSUE TITLE
check_http segmentation fault

### ISSUE THREAD

**Issue by barryo** [nagios-plugins/nagios-plugins#172]
Following this commit 224b1e50e75e5739851cc8ba4a52f4f07926fa54 `check_http` seg faults on multiple hosts that had been working fine for >10 years.

Here's the gdb log:

```
nagios-plugins-master/plugins]$ gdb check_http
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) r -H '192.0.2.166' -I '192.0.2.166'
Starting program: /home/test/nagios-plugins-master/plugins/check_http -H '192.0.2.166' -I '192.0.2.166'
[New LWP 100100]
[New Thread 801c06400 (LWP 100100/check_http)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 801c06400 (LWP 100100/check_http)]
check_http () at check_http.c:1209
1209      while (page[0] != '\r' || page[1] != '\n') {
Current language:  auto; currently minimal
```

The data from one sample HTTP site is:

```
$ curl -D - http://192.0.2.166/
HTTP/1.0 200 OK
Content-type: text/html

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
...
</html>
```

Reverting the above referenced commit corrected the issue.

Our platform is: FreeBSD 10.3-RELEASE-p4 and we were using package nagios-plugins-2.1.2,1

Thanks.

**Comment by jfrickson** [comment]
It looks to me like you're having problems because the server is sending `\n` instead of `\r\n` in and after the headers. So I reworked it.

It is fixed now in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/f3a519f8bd160f4fbb95944af239199757948196

**Comment by knweiss** [comment]
The code is still not correct. If `page` is the empty string the following for-loop loops forever:
```
  if (verbose)
    printf ("STATUS: %s\n", status_line);

  /* find header info and null-terminate it */
  header = page;
        for (;;) {
                if (!strncmp(page, "\r\n\r\n", 4) || !strncmp(page, "\n\n", 2))
                 break;
                while (*page == '\r' || *page == '\n') { ++page; }
    page += (size_t) strcspn (page, "\r\n");
    pos = page;
  }
```

(The indentation is inconsistent as well.)
