### ISSUE TITLE
check_snmp version 2.1.1 units label option outputs the label in the incorrect location for the performance data.

### ISSUE THREAD

**Issue by jfrickson** [nagios-plugins/nagios-plugins#180]
When specifying the units label option for check_snmp, the unit label is printed in the critical section of the performance data and not after the output of the data. See the example below.

```
./check_snmp -H 192.168.112.130 -P 2c -C public -o 1.3.6.1.2.1.4.31.1.1.35.1 -c 601 --units=%
SNMP OK - 432 % | iso.3.6.1.2.1.4.31.1.1.35.1=432;;601c%;;601; 
```

Migrated from http://api.nagios.com/tps/viewtask.php?task_id=7695 - please follow that link for details.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/655f55c486df31a7591de39bff67238dc3a4147e

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/nagios-plugins/nagios-plugins/commit/655f55c486df31a7591de39bff67238dc3a4147e

**Comment by michaje-gsc** [comment]
In what version was this fixed?  I still have the issue with version 2.4.9 of check_snmp
