### ISSUE TITLE
check_disk: Extraneous output

### ISSUE THREAD

**Issue by leeclemens** [nagios-plugins/nagios-plugins#472]
After upgrading EPEL's
`nagios-plugins-disk-2.2.1-16.20180725git3429dad.el7.x86_64` ->
`nagios-plugins-disk-2.2.1-17.20190829gitfb792ff.el7.x86_64`

I found extraneous output in the check's output. Unfortunately this makes it unreadable on a single line in IcingaWeb2, for example.

Testing with `git bisect` resulted in:
```
91ee0504f1a602cef3ed63f8ca1bc91ff17ed96b is the first bad commit
commit 91ee0504f1a602cef3ed63f8ca1bc91ff17ed96b
Author: madlohe <swolf@nagios.com>
Date:   Wed Aug 7 11:04:41 2019 -0500

    check_disk: add --combined-thresholds to resolve #267

:040000 040000 bab55c66b2ff52a3a0a8f3c6e73d1b11f05d1ac1 3137ca6ce51eaa77f28a3e9067ffd50fee882e19 M	plugins
```

It looks like 91ee0504f1a602cef3ed63f8ca1bc91ff17ed96b introduced some `printf`'s that were presumably used for local debugging.

Sample output (I snipped):
```
dfree_units 0 0
disk_result is 0dfree_units 0 0
disk_result is 0dfree_units 0 2
disk_result is 2dfree_units 0 0
disk_result is 0dfree_units 0 0
disk_result is 0DISK CRITICAL - free space: <SNIP>
```

**Comment by leeclemens** [comment]
I also created: https://bugzilla.redhat.com/show_bug.cgi?id=1752219

**Comment by imtek** [comment]
Got this same issue too, on nagios-plugins-disk-2.2.1-16.20180725git3429dad.el7.x86_64 no issues and nagios-plugins-disk-2.2.1-17.20190829gitfb792ff.el7.x86_64 results in this issue.

**Comment by widhalmt** [comment]
I got the same problem with `nagios-plugins-disk-2.2.1-17.20190829gitfb792ff.el6.x86_64` on CentOS 6 with Icinga 2 `icinga2-2.11.0-0.rc1.1.el6.icinga.x86_64`

**Comment by awkohr** [comment]
For me nagios-plugins-disk-2.2.1-17.20190829gitfb792ff.el7.x86_64 is only available in epel-testing and not the regular epel repo. However when I do a test for a specific like "/usr/lib64/nagios/plugins/check_disk  -w 10% -c 5% -p /boot,"  I am having similar problems With OK outputs outputting two lines instead of the expected one and an extraneous "disk_result is 0" before the Properly formatted status line.

Scince I am not the developer I will only make the following suggestions and not submit any code revisions. However in looking at 91ee050 (linked above) it looks like two lines are responsible for these issues.

line 402  is adding the dfree_units line/s and depending on the development teams long term intent with this line should either be removed entirely,  or have a "if (verbose_machine_output)" prepended to the line.
 
line 410 is responsible for the extraneous  prepending of "disk_result is 0"  in front of the second and if testing multiple disks the line after the disk it is testing. A similar decision should be made on how to handle this. However if there is an intention to keep this in the verbose output the current line 402 should also have a newline added to the print statement to make the output more readable. 
e.g. 'if (verbose_machine_output) printf("disk_result is %d\n", disk_result);'

thank you for taking the time to update the code.

**Comment by leeclemens** [comment]
@awkohr IMHO since this has already made it to "production", it should be removed (and I believe it will be potentially this week) first. If it was intended to be included as part of the verbose output it should be (re)introduced in a separate PR and reviewed, tested, etc as such.

**Comment by Madlohe** [comment]
Your opening comment is all correct, @leeclemens. Thanks for reporting this.

**Comment by hedenface** [comment]
"Why are development branches (not releases) being turned into packages?" I think is a better question here. Just my two cents.

**Comment by sebalaini** [comment]
any news about when this problem will be solved and a release date to update the package in Centos 7?

**Comment by awkohr** [comment]
@sabalaini. That would be a better questions for the fedora team. There is a bugzilla for that at https://bugzilla.redhat.com/show_bug.cgi?id=1752219

**Comment by leeclemens** [comment]
@sebalaini This comment hints that it could be this week, https://bugzilla.redhat.com/show_bug.cgi?id=1752272#c1 but the open bug is 1752219 as linked above.

**Comment by awkohr** [comment]
@hedenface As to why development builds are making it into “production” packages. On the Fedora IRC channel one of the members of the steering committee said that for epel-testing  7 repo it is acceptable to use maintenance/development releases to build packages. They use maintenance/development releases if it will fixing a bug their end users are experiencing, that has not yet made it into the projects official stable build, especially if stable builds are on a slower release scheduale.   It makes sense but as illustrated it can cause additional issues.

**Comment by sebalaini** [comment]
OK thanks :)

**Comment by ItsOnlyMeNL** [comment]
Just want to comment on this that this is also an issue on EL6 not only on EL7.

**Comment by awkohr** [comment]
@ItsOnlyMeNL. This git site site is the underlying source code and the maintenance source code that caused this has been corrected. The fedora/redhat/othe contributers epel team that builds the packages for EL6, need to rebuilt the packages and post them to epel. They are tracking this case in  bugzilla case 1752219 (link above. )  You may want to follow that bug and let them know the el6 version needs to be updated as well.

**Comment by ItsOnlyMeNL** [comment]
@awkohr Thanks.  i have read this to fast, didn't see the link, sorry

**Comment by tferic** [comment]
I got the same issue.
However, I am still getting correct alerting in Nagios 4.4.3.
I created a bunch of dummy files in a test machine's /boot, pushing the disk's usage above threshold, and got a proper alert.
That makes this issue less urgent for me, but still, it should be considered a bug, as the metrics aren't visible on the monitoring console anymore.

**Comment by leeclemens** [comment]
@tferic I'm not sure what you mean by alerting, but there was never an issue with the plugin determining the correct state and using the appropriate exit code. The issue is regarding the extraneous output printed to stdout.

**Comment by sawolf** [comment]
Locked because there's no further action to take in this repository.
I'm leaving the [bugzilla link](https://bugzilla.redhat.com/show_bug.cgi?id=1752219) one last time for anyone else who finds this and wants to get resolution for their packages.
