### ISSUE TITLE
check_http - Chunked Transfer Encoding leaks TCP header text into checked text, causing content checks to fail

### ISSUE THREAD

**Issue by alexs77** [nagios-plugins/nagios-plugins#76]
With check_http 1.4.16 and 2.0.3, I find, that sometimes my "content checks" fail. I invoke the tool like so:

    check_http -I 192.168.213.108 -H www.ariseprogram.org -s "footerContent" --sni

The check fails. When I add

 a "-v" to the check_http invocation, I find that the text indeed is "broken"; check_http uses the following as the text:

                <div class="footerCo
    305
    ntent cfx">

And that of course doesn't match. See https://github.com/alexs77/misc/blob/master/Bugreports/nagios-plugins/check_http.txt#L417-L419 for the full output of this check_http run.

My webserver at 192.168.213.108 however does NOT generate the text in this broken way. See https://github.com/alexs77/misc/blob/master/Bugreports/nagios-plugins/192.168.213.148.tcpdump for a tcpdump.

In this tcpdump, pay close attention to the tcp packets 40 and 41. 40 ends with the following "content":

[…]

	<div id="footer">
		<div class="footerCo

Packet 41 begins with:

    305
    ntent cfx">
    […]

The 305 is hex and is some sort of TCP "header", which shows how big the content is in this data segment.

Some more debugging has shown, that it doesn't matter whether I use "-s" or not. The text is always garbled. With "-s" or without.

And even more debugging with strace has shown, that there is a difference in how wget creates the socket and how check_http does it.

wget:

    socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
    …
    write(4, "GET / HTTP/1.1\r\nUser-Agent: Wget/1.13.4 (linux-gnu)\r\nAccept: */*\r\nHost: www.ariseprogram.org\r\nConnection: Keep-Alive\r\n\r\n", 120) = 120
    …
    read(3, "<scr… class=\"footerCont", 2139) = 1368
    read(3, "ent cfx\">\n\t…ml>", 771) = 771

check_http:

    socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
    …
    sendto(3, "GET / HTTP/1.1\r\nUser-Agent: Wget/1.13.4 (linux-gnu)\r\nConnection: close\r\nHost: www.ariseprogram.org\r\nAccept: */*\r\n\r\n", 115, 0, NULL, 0) = 115
    …
    read(3, "<scr… class=\"footerCo\r\n", 8191) = 1368
    read(3, "305\r\nntent cfx…", 8191) = 785

The difference might be, that check_http does "socket(…, IPPROTO_TCP)", whereas wget does "socket("…, IPPROTO_IP)".

This should not happen.

**Comment by alexs77** [comment]
This is a dupe of https://github.com/monitoring-plugins/monitoring-plugins/issues/1122: [monitoring-plugins: check_http asks for HTTP/1.1, but doesn't understand chunked [sf#2786808] #1122](https://github.com/monitoring-plugins/monitoring-plugins/issues/1122)

**Comment by koenwtje** [comment]
This has already been fixed in the 2.1 branch: https://github.com/nagios-plugins/nagios-plugins/commit/890d124e3ad908b0e553eaa6ef83b3b80c5a2dd9,  https://github.com/nagios-plugins/nagios-plugins/commit/f5cd931d01965991850d1e621d8f986ea1fd7f90

**Comment by jfrickson** [comment]
Closing per comment from koenwtje above and checking code.

**Comment by matrad** [comment]
Problem still existing in the 2.2 version of the plugin:

`</h
5
tml>

0`

`GET / HTTP/1.1
User-Agent: check_http/v2.2 (monitoring-plugins 2.2)
Connection: close
Host: xxxxxx:8080
X-Forwarded-Proto: https


http://xxxxxxx:8080/ is 153861 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Date: Tue, 19 Jun 2018 20:55:26 GMT
Server: Apache
Cache-Control: max-age=60, public, s-maxage=120
X-Location-Id: 2
X-Content-Type-ID: 23
X-Content-Type-Identifier: frontpage
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
**** CONTENT ****
2000
`
